# Generated by Django 3.1.7 on 2021-04-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('repo', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('location', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
